### ISSUE TITLE
Strange bug while trying to start the app

### ISSUE THREAD

**Issue by Firnen08** [MasonSakai/Iris-Full-Body-Tracking#4]
Starting
qt.core.qmetaobject.connectslotsbyname: QMetaObject::connectSlotsByName: No matching signal for on_cbxTrackerChest_clicked(bool)

**Comment by Firnen08** [comment]
Ah alright, i downloaded 1 version behind latest and it seemed to work, well to the extent of me not having enough time to actually try it out

**Comment by MasonSakai** [comment]
Well it seems like that one should work, since the newest one was an untested adjustment to the tracker layout. If it doesn't then no release will probably work (though you are free to try the first release), which is one of the reasons I want to rewrite it.
I have marked it as pre-release and will deal with it later, if at all before the rewrite.

**Comment by MasonSakai** [comment]
Yeah, the project, let alone the library, was never installed on my desktop, and project on the recovered drive does not seem stable enough to use, so it's not getting updated till the rewrite, which I guess I'll start working on soon.

Anyways, if you have any questions about use or something not working I'll try my best to help.
